---
openapi: 3.0.3
info:
 title: onecx-iam-kc-svc V1
 version: 1.0.0
servers:
 - url: "http://onecx-iam-kc-svc:8080"
tags:
 - name: AdminController
   description: IAM admin controller
paths:
 /v1/{userId}/roles:
  post:
   security:
    - oauth2: [ ocx-ia:all, ocx-ia:read ]
   tags:
    - AdminController
   summary: Get roles of user by id
   operationId: getUserRoles
   parameters:
    - name: userId
      in: path
      required: true
      description: Keycloak userId
      schema:
       type: string
   requestBody:
    content:
     "application/json":
      schema:
       $ref: '#/components/schemas/UserRolesSearchRequest'
   responses:
    200:
     description: OK
     content:
      "application/json":
       schema:
        $ref: '#/components/schemas/UserRolesResponse'
    400:
     description: Bad request
     content:
      application/json:
       schema:
        $ref: '#/components/schemas/ProblemDetailResponse'
 /v1/validate:
  post:
   security:
    - oauth2: [ ocx-ia:read ]
   tags:
    - AdminController
   summary: check if issuer is part of this svc
   operationId: validateIssuer
   requestBody:
    required: true
    content:
     "application/json":
      schema:
       $ref: '#/components/schemas/ValidateIssuerRequest'
   responses:
    200:
     description: OK
    404:
     description: issuer not found
    400:
     description: Bad request
     content:
      application/json:
       schema:
        $ref: '#/components/schemas/ProblemDetailResponse'
components:
 securitySchemes:
  oauth2:
   type: oauth2
   flows:
    clientCredentials:
     tokenUrl: https://oauth.simple.api/token
     scopes:
      ocx-ia:read: Grants read access
      ocx-ia:write: Grants write access
 schemas:
  ValidateIssuerRequest:
   type: object
   properties:
    issuer:
     type: string
  UserRolesSearchRequest:
   type: object
   properties:
    issuer:
     type: string
  UserRolesResponse:
   type: object
   properties:
    roles:
     type: array
     items:
      $ref: '#/components/schemas/Role'
  Role:
   type: object
   properties:
    name:
     type: string
    description:
     type: string
  ProblemDetailResponse:
   type: object
   properties:
    errorCode:
     type: string
    detail:
     type: string
    params:
     type: array
     items:
      $ref: '#/components/schemas/ProblemDetailParam'
    invalidParams:
     type: array
     items:
      $ref: '#/components/schemas/ProblemDetailInvalidParam'
  ProblemDetailParam:
   type: object
   properties:
    key:
     type: string
    value:
     type: string
  ProblemDetailInvalidParam:
   type: object
   properties:
    name:
     type: string
    message:
     type: string